---
name: pytest

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.12
          - 3.9
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth:

      - name: Set up Just for justfile usage
        uses: extractions/setup-just@v2
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests and coverage report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          python -m pip install --quiet --no-cache-dir --upgrade uv
          just coveralls